// courses.js — 10種の乗り物テーマデータ

const COURSES = {
  // 音名→周波数マッピング
  NOTE_FREQ: {
    'C3': 130.81, 'D3': 146.83, 'E3': 164.81, 'F3': 174.61, 'G3': 196.00, 'A3': 220.00, 'B3': 246.94,
    'C4': 261.63, 'D4': 293.66, 'E4': 329.63, 'F4': 349.23, 'G4': 392.00, 'A4': 440.00, 'B4': 493.88,
    'C5': 523.25, 'D5': 587.33, 'E5': 659.25, 'F5': 698.46, 'G5': 783.99, 'A5': 880.00, 'B5': 987.77,
    'Db3': 138.59, 'Eb3': 155.56, 'Gb3': 185.00, 'Ab3': 207.65, 'Bb3': 233.08,
    'Db4': 277.18, 'Eb4': 311.13, 'Gb4': 369.99, 'Ab4': 415.30, 'Bb4': 466.16,
    'Db5': 554.37, 'Eb5': 622.25, 'Gb5': 739.99, 'Ab5': 830.61, 'Bb5': 932.33,
    'F#3': 185.00, 'F#4': 369.99, 'F#5': 739.99,
    'C#3': 138.59, 'C#4': 277.18, 'C#5': 554.37,
    'G#3': 207.65, 'G#4': 415.30, 'G#5': 830.61,
    'D#3': 155.56, 'D#4': 311.13, 'D#5': 622.25,
    'A#3': 233.08, 'A#4': 466.16, 'A#5': 932.33,
  },

  // スケール定義（音名の配列）
  SCALES: {
    C_MAJOR_PENTA:  ['C4', 'D4', 'E4', 'G4', 'A4', 'C5', 'D5'],
    G_MAJOR:        ['G3', 'A3', 'B3', 'C4', 'D4', 'E4', 'F#4', 'G4'],
    D_MINOR_PENTA:  ['D4', 'F4', 'G4', 'A4', 'C5', 'D5'],
    F_MAJOR:        ['F3', 'G3', 'A3', 'Bb3', 'C4', 'D4', 'E4', 'F4'],
    F_LYDIAN:       ['F3', 'G3', 'A3', 'B3', 'C4', 'D4', 'E4', 'F4'],
    A_MINOR:        ['A3', 'B3', 'C4', 'D4', 'E4', 'F4', 'G4', 'A4'],
    E_MINOR_PENTA:  ['E4', 'G4', 'A4', 'B4', 'D5', 'E5'],
    C_MAJOR:        ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5'],
    D_MAJOR:        ['D4', 'E4', 'F#4', 'G4', 'A4', 'B4', 'C#5', 'D5'],
    A_MINOR_PENTA:  ['A3', 'C4', 'D4', 'E4', 'G4', 'A4', 'C5'],
  },

  // 乗り物定義
  vehicles: [
    {
      id: 'train',
      emoji: '🚃',
      name: 'でんしゃ',
      scale: 'C_MAJOR_PENTA',
      baseBPM: 80,
      waveType: 'square',
      bgColor1: '#87CEEB',
      bgColor2: '#E0F0FF',
      groundColor: '#8B7355',
      groundPattern: 'rail',
      obstacle: '🚧',
      obstacleName: 'ふみきり',
      doubleObstacle: '🚧🚧',
      coin: '⭐',
      goalEmoji: '🚉',
      goalText: 'えきに とうちゃく！',
      bgEmojis: ['🏠', '🌳', '⛰️'],
      unlockOrder: 0,
      bassNote: 'C3',
      flipX: true,
    },
    {
      id: 'bus',
      emoji: '🚌',
      name: 'バス',
      scale: 'G_MAJOR',
      baseBPM: 85,
      waveType: 'triangle',
      bgColor1: '#98FB98',
      bgColor2: '#F0FFF0',
      groundColor: '#666666',
      groundPattern: 'road',
      obstacle: '🚥',
      obstacleName: 'しんごう',
      doubleObstacle: '🏗️',
      coin: '⭐',
      goalEmoji: '🚏',
      goalText: 'バスてい とうちゃく！',
      bgEmojis: ['🏢', '🌳', '🏪'],
      unlockOrder: 1,
      bassNote: 'G3',
      flipX: true,
    },
    {
      id: 'firetruck',
      emoji: '🚒',
      name: 'しょうぼうしゃ',
      scale: 'D_MINOR_PENTA',
      baseBPM: 90,
      waveType: 'square',
      bgColor1: '#FFB6C1',
      bgColor2: '#FFF0F5',
      groundColor: '#555555',
      groundPattern: 'road',
      obstacle: '🔥',
      obstacleName: 'ほのお',
      doubleObstacle: '🔥🔥',
      coin: '⭐',
      goalEmoji: '💦🏠',
      goalText: 'しょうか かんりょう！',
      bgEmojis: ['🏢', '🏗️', '🏥'],
      unlockOrder: 4,
      bassNote: 'D3',
      flipX: true,
    },
    {
      id: 'taxi',
      emoji: '🚕',
      name: 'タクシー',
      scale: 'F_MAJOR',
      baseBPM: 85,
      waveType: 'triangle',
      bgColor1: '#FFDAB9',
      bgColor2: '#FFF8F0',
      groundColor: '#666666',
      groundPattern: 'road',
      obstacle: '🚧',
      obstacleName: 'こうじ',
      doubleObstacle: '🚧🚧',
      coin: '⭐',
      goalEmoji: '🏨',
      goalText: 'もくてきち とうちゃく！',
      bgEmojis: ['🏬', '🌳', '🏪'],
      unlockOrder: 5,
      bassNote: 'F3',
      flipX: true,
    },
    {
      id: 'ship',
      emoji: '⛴️',
      name: 'ふね',
      scale: 'F_LYDIAN',
      baseBPM: 70,
      waveType: 'sine',
      bgColor1: '#87CEEB',
      bgColor2: '#E6F3FF',
      groundColor: '#4169E1',
      groundPattern: 'wave',
      obstacle: '🌊',
      obstacleName: 'なみ',
      doubleObstacle: '🌊🌊',
      coin: '⭐',
      goalEmoji: '⚓',
      goalText: 'みなとに にゅうこう！',
      bgEmojis: ['🐟', '🐬', '☁️'],
      unlockOrder: 2,
      bassNote: 'F3',
      flipX: true,
    },
    {
      id: 'helicopter',
      emoji: '🚁',
      name: 'ヘリ',
      scale: 'A_MINOR',
      baseBPM: 95,
      waveType: 'sawtooth',
      bgColor1: '#B0E0E6',
      bgColor2: '#F0F8FF',
      groundColor: '#87CEEB',
      groundPattern: 'sky',
      obstacle: '☁️',
      obstacleName: 'くも',
      doubleObstacle: '⛈️',
      coin: '⭐',
      goalEmoji: '🏥',
      goalText: 'ヘリポートに ちゃくりく！',
      bgEmojis: ['☁️', '🌤️', '🐦'],
      unlockOrder: 6,
      bassNote: 'A3',
      flipX: true,
    },
    {
      id: 'police',
      emoji: '🚓',
      name: 'パトカー',
      scale: 'E_MINOR_PENTA',
      baseBPM: 100,
      waveType: 'square',
      bgColor1: '#2C3E50',
      bgColor2: '#34495E',
      groundColor: '#444444',
      groundPattern: 'road',
      obstacle: '🚨',
      obstacleName: 'バリケード',
      doubleObstacle: '🚨🚨',
      coin: '⭐',
      goalEmoji: '👮',
      goalText: 'はんにん かくほ！',
      bgEmojis: ['🏢', '🌙', '💡'],
      unlockOrder: 7,
      bassNote: 'E3',
      flipX: true,
    },
    {
      id: 'bulldozer',
      emoji: '🚜',
      name: 'ブルドーザー',
      scale: 'C_MAJOR',
      baseBPM: 75,
      waveType: 'triangle',
      bgColor1: '#DEB887',
      bgColor2: '#FFF8DC',
      groundColor: '#CD853F',
      groundPattern: 'dirt',
      obstacle: '🪨',
      obstacleName: 'いわ',
      doubleObstacle: '🪨🪨',
      coin: '⭐',
      goalEmoji: '🛣️',
      goalText: 'どうろ かんせい！',
      bgEmojis: ['⛰️', '🏗️', '🌳'],
      unlockOrder: 3,
      bassNote: 'C3',
      flipX: true,
    },
    {
      id: 'airplane',
      emoji: '✈️',
      name: 'ひこうき',
      scale: 'D_MAJOR',
      baseBPM: 90,
      waveType: 'sine',
      bgColor1: '#87CEEB',
      bgColor2: '#E0F0FF',
      groundColor: '#FFFFFF',
      groundPattern: 'cloud',
      obstacle: '🐦',
      obstacleName: 'とり',
      doubleObstacle: '🦅',
      coin: '⭐',
      goalEmoji: '🛬',
      goalText: 'くうこうに ちゃくりく！',
      bgEmojis: ['☁️', '🌤️', '✨'],
      unlockOrder: 8,
      bassNote: 'D3',
      flipX: false,
    },
    {
      id: 'racecar',
      emoji: '🏎️',
      name: 'レースカー',
      scale: 'A_MINOR_PENTA',
      baseBPM: 110,
      waveType: 'sawtooth',
      bgColor1: '#2d2d2d',
      bgColor2: '#1a1a2e',
      groundColor: '#444444',
      groundPattern: 'road',
      obstacle: '🛢️',
      obstacleName: 'ドラムかん',
      doubleObstacle: '🛢️🛢️',
      coin: '⭐',
      goalEmoji: '🏁',
      goalText: 'ゴール！ ゆうしょう！',
      bgEmojis: ['🏁', '🔥', '✨'],
      unlockOrder: 9,
      bassNote: 'A3',
      flipX: true,
    },
  ],

  // アンロック順でソートして取得
  getUnlockOrder() {
    return [...this.vehicles].sort((a, b) => a.unlockOrder - b.unlockOrder);
  },

  // IDで乗り物を取得
  getVehicle(id) {
    return this.vehicles.find(v => v.id === id);
  },

  // ステージ順で乗り物を取得（unlockOrder順）
  getStageVehicle(stage) {
    const ordered = this.getUnlockOrder();
    return ordered[Math.min(stage - 1, ordered.length - 1)];
  },

  // ステージ難易度パラメータ（ステージ1〜10）
  getStageParams(stage) {
    const vehicle = this.getStageVehicle(stage);
    const t = (stage - 1) / 9; // 0.0 〜 1.0
    return {
      bpm: vehicle.baseBPM + Math.round(t * 15),
      restRatio: 0.5 - t * 0.25,           // 0.50 → 0.25
      noteCount: Math.round(8 + t * 18),    // 8 → 26（後半は長いステージ）
      scrollSpeed: 50 + t * 50,             // 50 → 100 px/s
      approachTime: 3.5 - t * 0.8,         // 3.5 → 2.7 s
      allowTightPair: stage >= 7,
      tightPairChance: stage >= 9 ? 0.3 : stage >= 7 ? 0.15 : 0,
      tightPairGap: 0.75,
      // 大障害物: ステージ6から登場、後半ほど多く
      bigObstacleChance: stage >= 10 ? 0.5 : stage >= 9 ? 0.4 : stage >= 8 ? 0.35 : stage >= 7 ? 0.25 : stage >= 6 ? 0.15 : 0,
    };
  },

  TOTAL_STAGES: 10,
};
